# -*- coding: utf-8 -*-
"""Open CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PiqKzlHZH9F8CQDVQih1XplzWIv2NDJO

**OPEN CV** -- CV Stands for Computer vision.It is a module which is used for image editing, object detection,moving object detection etc..
"""

from google.colab import drive
drive.mount('/content/gdrive')

#Reading image
import cv2
from google.colab.patches import cv2_imshow
x=cv2.imread("/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg")
cv2_imshow(x)

#print the image in array fromat
print(x)

print(x.shape)

print(x.dtype)

#duplicating image
cv2.imwrite("/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg",x)

#Rotating image
image=cv2.rotate(x,cv2.ROTATE_90_CLOCKWISE)
cv2_imshow(image)

rot180=cv2.rotate(x,cv2.ROTATE_180)
cv2_imshow(image)

rot270=cv2.rotate(x,cv2.ROTATE_90_COUNTERCLOCKWISE)
cv2_imshow(rot270)

#Rotate the image by angle
#shape of image interms of pixels
(rows,cols)=x.shape[:2]
""" get Rotation matrix 2D creates a matrix needed for transformation. we want matrix for rotation w.r.t center to 45 degree without scaling"""
M=cv2.getRotationMatrix2D((cols/2,rows/2),45,1)
res=cv2.warpAffine(x,M,(cols,rows))
cv2_imshow(res)

#Rotate the image by angle
#shape of image interms of pixels
(rows,cols)=x.shape[:2]
""" get Rotation matrix 2D creates a matrix needed for transformation. we want matrix for rotation w.r.t center to 45 degree without scaling"""
M=cv2.getRotationMatrix2D((cols/2,rows/2),75,1)
res=cv2.warpAffine(x,M,(cols,rows))
cv2_imshow(res)

#Open CV image Resizing
import cv2
import numpy as np
import matplotlib.pyplot as plt
half=cv2.resize(x,(0,0),fx=0.1,fy=0.1)
bigger=cv2.resize(x,(1050,1610))
stretch_near=cv2.resize(x,(780,540),interpolation=cv2.INTER_NEAREST)
titles=["Original","Half","Bigger","Interpolation Nearest"]
images=[image, half, bigger,stretch_near]
count=4
for i in range(count):
  plt.subplot(2,3,i+1)
  plt.title(titles[i])
  plt.imshow(images[i])
plt.show()

# organizing imports
import cv2
import numpy as np
image1 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/star.jpg')
image2 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/dot.jpg')
weightedSum = cv2.addWeighted(image1, 0.5, image2, 0.4, 0)
cv2_imshow(weightedSum)

# subtraction of pixels of two images(Arithmetical operations)

# organizing imports
import cv2
import numpy as np
image1 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/star.jpg')
image2 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/dot.jpg')
sub = cv2.subtract(image1, image2)
cv2_imshow(sub)

# arithmetic operation bitwise AND of two images
import cv2
import numpy as np
img1 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/input1.png')
img2 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/input2.png')
dest_and = cv2.bitwise_and(img2, img1, mask = None)
cv2_imshow(dest_and)

# bitwise OR of two images
import cv2
import numpy as np
img1 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/input1.png')
img2 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/input2.png')
dest_or = cv2.bitwise_or(img2, img1, mask = None)
cv2_imshow(dest_or)

# bitwise XOR of two images
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
img1 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/input1.png')
img2 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/input2.png')
dest_xor = cv2.bitwise_xor(img1, img2, mask = None)
cv2_imshow(dest_xor)

# bitwise NOT on input image
import cv2
import numpy as np
img1 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/input1.png')
img2 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/input2.png')
dest_not1 = cv2.bitwise_not(img1, mask = None)
dest_not2 = cv2.bitwise_not(img2, mask = None)
cv2_imshow(dest_not1)
cv2_imshow(dest_not2)

#OpenCV Image Translation

import cv2
import numpy as np
image = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg')
height, width = image.shape[:2]
quarter_height, quarter_width = height / 4, width / 4
T = np.float32([[1, 0, quarter_width], [0, 1, quarter_height]])
img_translation = cv2.warpAffine(image, T, (width, height))
cv2_imshow(img_translation)

#Converting color image to grayscale
image=cv2.imread("/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg")
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

#Edge detection
import cv2
img=cv2.imread("/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg")
edges=cv2.Canny(img,100,300)#Canny edge detection
cv2_imshow(edges)

"""**THESHOLDING**"""

#OpenCV Simple Thresholding
import cv2
import numpy as np
image1=cv2.imread("/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg")
img=cv2.cvtColor(image1,cv2.COLOR_BGR2GRAY)
ret,thresh1=cv2.threshold(img,120,255,cv2.THRESH_BINARY)
ret,thresh2=cv2.threshold(img,120,255,cv2.THRESH_BINARY_INV)
ret,thresh3=cv2.threshold(img,120,255,cv2.THRESH_TRUNC)
ret,thresh4=cv2.threshold(img,120,255,cv2.THRESH_TOZERO)
ret,thresh5=cv2.threshold(img,120,255,cv2.THRESH_TOZERO_INV)
cv2_imshow(thresh1)

cv2_imshow(thresh2)

cv2_imshow(thresh3)

cv2_imshow(thresh4)

cv2_imshow(thresh5)

"""**ADAPTIVE THRESHOLDING**"""

#Adaptive Thresholding
import cv2
import numpy as np
image1=cv2.imread("/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg")
imag=cv2.cvtColor(image1,cv2.COLOR_BGR2GRAY)
thresh1=cv2.adaptiveThreshold(imag,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,199,c)
cv2_imshow(thresh1)

img = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)

thresh2=cv2.adaptiveThreshold(imag,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,199,c)
cv2_imshow(thresh2)

#OpenCV Otsu Thresholding

# Python program to illustrate
# Otsu thresholding type on an image

# organizing imports
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# path to input image is specified and
# image is loaded with imread command
image1 = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg')

# cv2.cvtColor is applied over the
# image input with applied parameters
# to convert the image in grayscale
img = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)

# applying Otsu thresholding
# as an extra flag in binary
# thresholding
ret, thresh1 = cv2.threshold(img, 120, 255, cv2.THRESH_BINARY +
                             cv2.THRESH_OTSU)

# the window showing output image
# with the corresponding thresholding
# techniques applied to the input image
cv2_imshow(thresh1)

"""**BLUR**"""

#OpenCV Blur Image
import cv2
import numpy as np
image = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg')
cv2_imshow(image)

# Gaussian Blur
Gaussian = cv2.GaussianBlur(image, (7, 7), 0)
cv2_imshow(Gaussian)

# Median Blur
median = cv2.medianBlur(image, 5)
cv2_imshow(median)

# Bilateral Blur
bilateral = cv2.bilateralFilter(image, 9, 70, 70)
cv2_imshow(bilateral)

#OpenCV Image Contour
import cv2
import numpy as np
image = cv2.imread('/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
edged = cv2.Canny(gray, 30, 200)
contours, hierarchy = cv2.findContours(edged,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
cv2_imshow(edged)

print("Number of Contours found = " + str(len(contours)))
cv2.drawContours(image, contours, -1, (0, 255, 0), 3)
cv2_imshow(image)

#OpenCV Erosion and Dilation

# Python program to demonstrate erosion and
# dilation of images.
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
import os

# Fallback file path targeting the verified Google Drive image
img_path = '/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg'
if not os.path.exists(img_path):
    # Fallback to local workspace files if drive path is unavailable
    img_path = 'car.jpg'

# Reading the input image in grayscale
img = cv2.imread(img_path, 0)

if img is None:
    raise FileNotFoundError("Input image could not be loaded. Please check the file path.")

# Taking a matrix of size 5 as the kernel
kernel = np.ones((5,5), np.uint8)

# Apply erosion and dilation
img_erosion = cv2.erode(img, kernel, iterations=1)
img_dilation = cv2.dilate(img, kernel, iterations=1)

print("Original Image (Grayscale):")
cv2_imshow(img)

print("Erosion Output:")
cv2_imshow(img_erosion)

print("Dilation Output:")
cv2_imshow(img_dilation)

import numpy as np
import cv2
from google.colab.patches import cv2_imshow
import os

# Define verified image path in the workspace
img_path = 'car.jpg'
if not os.path.exists(img_path):
    # Fallback to the Google Drive version if local file isn't found
    img_path = '/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg'

# Read the query image and train image
query_img = cv2.imread(img_path)
train_img = cv2.imread(img_path)

if query_img is None:
    raise FileNotFoundError("Target image could not be loaded. Please ensure 'car.jpg' is uploaded.")

# Convert it to grayscale
query_img_bw = cv2.cvtColor(query_img, cv2.COLOR_BGR2GRAY)
train_img_bw = cv2.cvtColor(train_img, cv2.COLOR_BGR2GRAY)

# Initialize the ORB detector algorithm
orb = cv2.ORB_create()

# Now detect the keypoints and compute the descriptors
queryKeypoints, queryDescriptors = orb.detectAndCompute(query_img_bw, None)
trainKeypoints, trainDescriptors = orb.detectAndCompute(train_img_bw, None)

# Initialize the Matcher for matching keypoints
matcher = cv2.BFMatcher()
matches = matcher.match(queryDescriptors, trainDescriptors)

# Draw the matches to the final image
final_img = cv2.drawMatches(query_img, queryKeypoints,
                            train_img, trainKeypoints, matches[:20], None)

final_img = cv2.resize(final_img, (1000, 650))

# Show the final image in Colab
cv2_imshow(final_img)

import cv2
from matplotlib import pyplot as plt
import os

image_path = '/content/cats_dogs.jpg'

# Fallback to 'car.jpg' if the requested image does not exist
if not os.path.exists(image_path):
    image_path = '/content/car.jpg'

image = cv2.imread(image_path)

if image is None:
    raise FileNotFoundError("Image file could not be found or loaded. Please upload the image first!")

resized_image = cv2.resize(image, (1900, 800))
resized_image_rgb = cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB)
plt.imshow(resized_image_rgb)
plt.title('Original Image (Resized)')
plt.axis('off')
plt.show()

Gaussian = cv2.GaussianBlur(resized_image, (15, 15), 0)
Gaussian_rgb = cv2.cvtColor(Gaussian, cv2.COLOR_BGR2RGB)
plt.imshow(Gaussian_rgb)
plt.title('Gaussian Blurred Image')
plt.axis('off')
plt.show()

median = cv2.medianBlur(resized_image, 11)
median_rgb = cv2.cvtColor(median, cv2.COLOR_BGR2RGB)

plt.imshow(median_rgb)
plt.title('Median Blurred Image')
plt.axis('off')
plt.show()

bilateral = cv2.bilateralFilter(resized_image, 15, 150, 150)
bilateral_rgb = cv2.cvtColor(bilateral, cv2.COLOR_BGR2RGB)

plt.imshow(bilateral_rgb)
plt.title('Bilateral Blurred Image')
plt.axis('off')
plt.show()

#Using the cv2.cvtColor() function

import cv2
import os
from google.colab.patches import cv2_imshow

# Fallback file path targeting a verified image in the workspace
img_path = 'car.jpg'
if not os.path.exists(img_path):
    img_path = '/content/gdrive/My Drive/Colab Notebooks/jpg/01.jpg'

image = cv2.imread(img_path)

if image is None:
    raise FileNotFoundError("Could not find or load the target image. Please upload 'car.jpg' first!")

gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

print("Grayscale Image:")
cv2_imshow(gray_image)

#Using the pixel manipulation (Average method)
#This method converts an image to grayscale by averaging the contributions of color channels (RGB). It’s a simple approach but not very accurate because it treats all colors equally, ignoring how the human eye perceives brightness.

import cv2
import os
from google.colab.patches import cv2_imshow

# Fallback file path targeting a verified image in the workspace
img_path = 'C:\\Documents\\full_path\\tomatoes.jpg'
if not os.path.exists(img_path):
    img_path = 'car.jpg'

img = cv2.imread(img_path)

if img is None:
    raise FileNotFoundError("Could not find or load the target image 'car.jpg'!")

rows, cols = img.shape[:2]

for i in range(rows):
    for j in range(cols):
        # Convert values to int to prevent overflow when summing channels
        gray = (int(img[i, j, 0]) + int(img[i, j, 1]) + int(img[i, j, 2])) // 3
        img[i, j] = [gray, gray, gray]

print("Grayscale Image (Average Method):")
cv2_imshow(img)

#Weighted Method (Recommended)
#This method uses standard luminance weights (0.2989R + 0.5870G + 0.1140B) to account for human visual sensitivity—more to green, less to red, least to blue. It produces a more realistic and visually accurate grayscale image.

import cv2
import os
from google.colab.patches import cv2_imshow

# Fallback file path targeting a verified image in the workspace
img_path = 'C:\\Documents\\full_path\\tomatoes.jpg'
if not os.path.exists(img_path):
    img_path = 'car.jpg'

img_weighted = cv2.imread(img_path)

if img_weighted is None:
    raise FileNotFoundError("Could not find or load the target image 'car.jpg'!")

rows, cols = img_weighted.shape[:2]

for i in range(rows):
    for j in range(cols):
        # BGR representation in OpenCV: index 2 = Red, 1 = Green, 0 = Blue
        gray = 0.2989 * int(img_weighted[i, j][2]) + 0.5870 * int(img_weighted[i, j][1]) + 0.1140 * int(img_weighted[i, j][0])
        img_weighted[i, j] = [int(gray), int(gray), int(gray)]

print("Grayscale Image (Weighted Method):")
cv2_imshow(img_weighted)

"""**FACE DETECTION**"""

pip install opencv-python

pip install opencv-contrib-python

import cv2
from google.colab.patches import cv2_imshow

from google.colab import files
uploaded=files.upload()

#Convert to gray scale
nparr = np.frombuffer(uploaded['12.jpg'], np.uint8)
img_12 = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
gray=cv2.cvtColor(img_12,cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

!wget https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml

import cv2
import os
from google.colab.patches import cv2_imshow

# Define path
img_path = '/content/gdrive/My Drive/Colab Notebooks/jpg/9.jpg'

# Check if file exists, otherwise try fallback or notify
if not os.path.exists(img_path):
    # Look for a fallback image in the local workspace if the drive path is invalid
    if os.path.exists('car6.jpg'):
        print("Warning: Target image not found in Google Drive. Using local 'car6.jpg' as a fallback.")
        img_path = 'car6.jpg'

img = cv2.imread(img_path)

if img is None:
    raise FileNotFoundError(f"Could not find or load the image at '{img_path}'. "
                            "Please make sure Google Drive is properly mounted and the file path is correct, "
                            "or upload the image directly to your Colab workspace.")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Download the cascade classifier XML file if not present
cascade_filename = 'haarcascade_frontalface_default.xml'
if not os.path.exists(cascade_filename):
    print(f"Downloading {cascade_filename}...")
    !wget -O {cascade_filename} https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/{cascade_filename}

face_cascade = cv2.CascadeClassifier(cascade_filename)

# Check if the cascade classifier loaded successfully
if face_cascade.empty():
    raise IOError(f"Could not load face cascade classifier from {cascade_filename}. "
                  "Ensure the file exists and is valid.")

# Detect faces
faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

# Draw rectangles around the detected faces
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

# Display the image with detected faces
cv2_imshow(img)

#Eye detection
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_eye.xml")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

eyes = eye_cascade.detectMultiScale(gray, 1.1, 5)

for (x, y, w, h) in eyes:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255,0,0), 2)

cv2_imshow(img)

#Smile Detection
smile_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_smile.xml")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

smiles = smile_cascade.detectMultiScale(gray, 1.8, 20)

for (x, y, w, h) in smiles:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0,0,255), 2)

cv2_imshow(img)

#full body detection
import cv2
import os
from google.colab.patches import cv2_imshow

# Correct the cascade path using the built-in OpenCV helper
body_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_fullbody.xml")

# Define the primary image path
img_path = "/content/gdrive/My Drive/Colab Notebooks/jpg/9.jpg"

# Fallback to local 'car6.jpg' if the target image does not exist
if not os.path.exists(img_path):
    if os.path.exists("car6.jpg"):
        print("Warning: '/content/gdrive/My Drive/Colab Notebooks/jpg/9.jpg' not found. Falling back to local 'car6.jpg'.")
        img_path = "car6.jpg"

img = cv2.imread(img_path)

if img is None:
    raise FileNotFoundError(f"Could not find or load any image at '{img_path}'. Please upload your target image.")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

bodies = body_cascade.detectMultiScale(gray, 1.1, 3)

for (x, y, w, h) in bodies:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0,255,255), 2)

cv2_imshow(img)

import cv2
import os
from google.colab.patches import cv2_imshow

# Ensure classifiers are initialized correctly
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_eye.xml")

# Define the primary image path
img_path = "/content/gdrive/My Drive/Colab Notebooks/jpg/9.jpg"

# Fallback to local 'car6.jpg' if the target image does not exist
if not os.path.exists(img_path):
    if os.path.exists("car6.jpg"):
        print("Warning: '/content/gdrive/My Drive/Colab Notebooks/jpg/9.jpg' not found. Falling back to local 'car6.jpg'.")
        img_path = "car6.jpg"

img = cv2.imread(img_path)

if img is None:
    raise FileNotFoundError(f"Could not find or load any image at '{img_path}'. Please upload your target image.")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray, 1.1, 5)

for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0,255,0), 2)

    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]

    eyes = eye_cascade.detectMultiScale(roi_gray)

    for (ex, ey, ew, eh) in eyes:
        cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (255,0,0), 2)

cv2_imshow(img)

"""**CAR DETECTION**"""

from google.colab import files

uploaded = files.upload()

#car detection
import cv2
from google.colab.patches import cv2_imshow
car_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_car.xml")
img=cv2.imread("car7.jpg")
cv2_imshow(img)

pip install opencv-python -q

import cv2
from google.colab.patches import cv2_imshow
car_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_car.xml")
import os

cascade_path = cv2.data.haarcascades + "haarcascade_car.xml"

if not os.path.exists(cascade_path):
    print("Downloading car cascade...")

    !wget -O car.xml https://raw.githubusercontent.com/andrewssobral/vehicle_detection_haarcascades/master/cars.xml
    cascade_path = "car.xml"

car_cascade = cv2.CascadeClassifier(cascade_path)
img = cv2.imread("car1.jpg") # Changed from 'cars (1).jpg' to 'car.jpg'

if img is None:
    raise FileNotFoundError("Image 'car.jpg' not found. Please upload the image.")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cars = car_cascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=2,
    minSize=(30, 30)
)
for (x, y, w, h) in cars:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 255), 2)
    cv2.putText(img, "Car", (x, y-5),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6,
                (0, 255, 255), 2)
cv2_imshow(img)

pip install  easyocr

pip install ultralytics

from google.colab import drive
drive.mount('/content/gdrive')

!pip install ultralytics -q
import cv2
import easyocr
import os
from ultralytics import YOLO
from google.colab.patches import cv2_imshow
from google.colab import drive

# Mount Google Drive to access images
drive.mount('/content/gdrive', force_remount=True)

model = YOLO("yolov8n.pt")

# Define the correct path to the car image in Google Drive
img_path = "/content/gdrive/My Drive/Colab Notebooks/jpg/car2.jpg"

# Fallback to local directory if not found in Google Drive
if not os.path.exists(img_path):
    img_path = "car.jpg"

img = cv2.imread(img_path)

if img is None:
    raise FileNotFoundError(f"Could not find or load the image at '{img_path}'. Please upload 'car.jpg' to your Google Drive folder or Colab workspace.")

results = model(img)
for r in results:
    for box in r.boxes.xyxy:
        x1, y1, x2, y2 = map(int, box)
        crop = img[y1:y2, x1:x2]
        cv2_imshow(crop)

reader = easyocr.Reader(['en'])
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
text = reader.readtext(gray)

for (bbox, txt, prob) in text:
    print("Detected Text:", txt)

import cv2
import os
from google.colab.patches import cv2_imshow
cascade_path = "haarcascade_russian_plate_number.xml"

if not os.path.exists(cascade_path):
    print("Downloading number plate cascade...")
    !wget -O haarcascade_russian_plate_number.xml \
    https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_russian_plate_number.xml

    cascade_path = "haarcascade_russian_plate_number.xml"

plate_cascade = cv2.CascadeClassifier(cascade_path)

# Define the primary image path in Google Drive
img_path = "/content/gdrive/My Drive/Colab Notebooks/jpg/car.jpg"

# Fallback to the locally uploaded 'car.jpg' if the Drive path does not exist
if not os.path.exists(img_path):
    if os.path.exists("car.jpg"):
        img_path = "car.jpg"

img = cv2.imread(img_path)

if img is None:
    raise FileNotFoundError("Image 'car.jpg' not found. Please upload 'car.jpg' to your workspace first!")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
plates = plate_cascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=4,
    minSize=(25, 25)
)
for (x, y, w, h) in plates:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
    cv2.putText(img, "Number Plate", (x, y-10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7,
                (0, 255, 0), 2)
cv2_imshow(img)

from google.colab import drive
drive.mount('/content/gdrive')

import cv2
import easyocr
from google.colab.patches import cv2_imshow
import os
img = cv2.imread("/content/gdrive/My Drive/Colab Notebooks/jpg/car10.jpg")
if img is None:
    raise FileNotFoundError("Image not found. Upload 'cars (1).jpg' first!")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY);

# Detect license plates using the previously loaded cascade classifier
plates = plate_cascade.detectMultiScale(gray,scaleFactor=1.1,minNeighbors=4,minSize=(25, 25))
reader = easyocr.Reader(['en'])
print("Detected License Plates and Extracted Text:")
for (x, y, w, h) in plates:
    # Draw rectangle around the detected plate
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
    cv2.putText(img, "Number Plate", (x, y-10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7,
                (0, 255, 0), 2)

    # Crop the license plate region
    cropped_plate = img[y:y+h, x:x+w]

    # Convert the cropped plate to grayscale for OCR if easyocr expects it
    # Although easyocr can handle color, grayscale might sometimes improve results
    cropped_plate_gray = cv2.cvtColor(cropped_plate, cv2.COLOR_BGR2GRAY)

    # Perform OCR on the cropped plate
    text_results = reader.readtext(cropped_plate_gray)

    detected_texts = [text for (bbox, text, prob) in text_results]
    if detected_texts:
        print(f"  Plate at ({x},{y},{w},{h}): {', '.join(detected_texts)}")
    else:
        print(f"  Plate at ({x},{y},{w},{h}): No text detected")

# Display the image with detected plates
cv2_imshow(img)

