# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EhTYZaQVvb_2NQ3OrVG-_bXGliL_hws

**MATPLOTLIB** - Matplotlib is a plotting library for the python programming language and its numerical mathematics extension numpy.
"""

import matplotlib
import matplotlib.pyplot as plt
print("matplotlib version:",matplotlib.__version__)

print(plt.style.available[:])

print(plt.style.available[:10])

#Line plot
import matplotlib
import matplotlib.pyplot as plt
plt.plot([1,2,3,4,],[2,4,3,5])
plt.title("Basic Line Plot")
plt.xlabel("X")
plt.ylabel("y")
plt.show()

#Line Plot with markers
import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[2,3,5,7,7]
plt.plot(x,y,marker="o")
plt.title("Line Plot with Markers")
plt.xlabel("X Values")
plt.ylabel("Y Values")
plt.show()

#Line plot Customization
import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[2,3,5,7,7]
plt.plot(x,y,color="teal",linestyle="--",linewidth=2,marker="o",markersize=7,markerfacecolor="white")
plt.title("Customization Line plot")
plt.xlabel("X values")
plt.ylabel("y values")
plt.grid(True,alpha=0.2)
plt.show()

#Multiple lines & Filled Array
import matplotlib.pyplot as plt
import numpy as np
x=np.arange(0,6)
y1=x**2
y2=2*x+1
plt.plot(x,y1,label="x2")
plt.plot(x,y2,label="2x+1")
plt.fill_between(x,y1,y2,alpha=0.2)
plt.legend()
plt.title("Multiple lines with fill")
plt.show()

#Bar charts
import matplotlib.pyplot as plt
import numpy as np
categories=["Python","Java","SQL","Excel"]
values=[85,70,90,75]
plt.bar(categories,values)
plt.title("Bar chart")
plt.ylabel("Score")
plt.show()
plt.barh(categories,values)
plt.title("Horizontal Bar Chart")
plt.xlabel("Score")
plt.show()

#Grouped & Stacked Bar Chart
import matplotlib.pyplot as plt
import numpy as np
x=np.arange(4)
a=[20,35,30,35]
b=[25,32,34,20]
width=0.35
plt.bar(x-width/2,a,width,label="A")
plt.bar(x+width/2,b,width,label="B")
plt.xticks(x,["Q1","Q2","Q3","Q4"])
plt.legend()
plt.title("Grouped Bar Chart")
plt.show()
plt.bar(x,a,b,label="A")
plt.bar(x,b,bottom=a,label="B")
plt.xticks(x,["Q1","Q2","Q3","Q4"])
plt.legend()
plt.title("Stacked Bar chart")
plt.show()

#Histograms
import matplotlib.pyplot as plt
import numpy as np
rng=np.random.default_rng(42)
data=rng.normal(50,10,100)
plt.hist(data,bins=20,edgecolor="black")
plt.title("Histogram")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()
plt.hist(data,bins=20,density=True,alpha=0.7)
plt.title("Density histogram")
plt.show()

#Scatter plot
import matplotlib.pyplot as plt
import numpy as np
rng=np.random.default_rng(42)
x=rng.normal(size=100)
y=2*x+rng.normal(size=100)
plt.scatter(x,y,s=50,alpha=0.7)
plt.title("Scatter plot")
plt.xlabel("X")
plt.ylabel("y")
plt.show()
sizes=np.abs(y)*80+20
plt.scatter(x,y,s=sizes,c=y,cmap="viridis",alpha=0.7)
plt.colorbar(label="y")
plt.title("Scatter with size and colors")
plt.show()

"""**BOX PLOT **- Box plot is also known as whisker plot.Used to dispay the summary.


**Violin Plot** - Represent the distribution of data.
"""

#Statistical and distribution charts
import matplotlib.pyplot as plt
import numpy as np
rng=np.random.default_rng(42)
a=rng.normal(50,8,100)
b=rng.normal(55,10,100)
plt.boxplot([a,b],tick_labels=["A","B"])
plt.title("Box Plot")
plt.show()
plt.violinplot([a,b],showmeans=True)
plt.xticks([1,2],["A","B"])
plt.title("Violin Plot")
plt.show()

"""**Exploded** - Exploded means it will seperate the highest value from remaining the values."""

import matplotlib.pyplot as plt
labels=["Python","Java","SQL","Excel"]
values=[40,25,20,15]
plt.pie(values,labels=labels,autopct="%1.1f%%",startangle=90)
plt.title("Pie chart")
plt.axis("equal")
plt.show()
plt.pie(values,labels=labels,explode=[0.08,0,0,0],autopct="%1.1f%%",shadow=False)
plt.title("Exploded Pie Chart")
plt.show()

"""**STEM PLOT** - Classify other discrete or continuous variables.

**STEP PLOT **- Shows how values changes at specific points.

**FILLED PLOT** - Also known as filled area plot or an area plot or an area chart. Used to show the data with filled regions.
"""

#Stem, Step, Area plots.
import matplotlib.pyplot as plt
import numpy as np
x=np.arange(1,6)
y=[2,4,3,5,4]
plt.stem(x,y)
plt.title("Stem Plot")
plt.show()
plt.step(x,y,where="mid")
plt.title("Step plot")
plt.show()

"""**ERROR BAR** - Visualize the variability of plotted data."""

#Error Bar & Stacked plot
import matplotlib.pyplot as plt
import numpy as np
x=np.arange(1,6)
y=[2,4,3,5,4]
errors=[0.2,0.4,0.3,0.5,0.25]
plt.errorbar(x,y,yerr=errors,fmt="o-",capsize=4)
plt.title("Error Bar Plot")
plt.show()
#Stack plot
plt.stackplot(x,[1,2,3,2,4],[2,1,2,3,2],labels=["A","B"])
plt.legend()
plt.title("Stack plot")
plt.show()

"""**Polar plot** - Used to produce graph that is related to either direction or to a some period cycle.

**Quiver Plot **- Displays arrows representing vectors at a specific points in a 2D or 3D space.
"""

#Polar plot & Specialized 2-D plots
import numpy as np
import matplotlib.pyplot as plt
theta=np.linspace(0,2*np.pi,500)
r=1+np.cos(theta)
ax=plt.subplot(projection="polar")
ax.plot(theta,r)
ax.set_title("Polar Plot")
plt.show()
theta=np.linspace(0,2*np.pi,200)
u=np.cos(theta)
v=np.sin(theta)
plt.figure()
plt.quiver([0],[0],[1],[1],angles="xy",scale_units="xy",scale=1)
plt.xlim(-1,2)
plt.ylim(-1,2)
plt.title("Quiver Plot")
plt.grid()
plt.show()

"""**SUB PLOTS **- Producing multiple types of plots on a single screen is called subplot."""

#Subplots
import matplotlib.pyplot as plt
import numpy as np
x=np.arange(10)
fig,axes=plt.subplots(2,2,figsize=(9,6))
axes[0,0].plot(x,x**2)
axes[0,0].set_title("Line")
axes[0,1].bar(["A","B","C"],[3,5,4])
axes[0,1].set_title("Bar")
axes[1,0].scatter(x,x+np.random.default_rng(1).normal(size=10))
axes[1,0].set_title("Scatter")
axes[1,1].hist(np.random.default_rng(2).normal(size=500),bins=20)
axes[1,1].set_title("Histogram")
fig.suptitle("Subplots")
fig.tight_layout()
fig.show()

#Labels,Legends,Ticks & Annotations
import matplotlib.pyplot as plt
import numpy as np
x=np.arange(6)
y=[2,4,3,5,7,8]
fig,ax=plt.subplots()
ax.plot(x,y,marker="o",label="Sales")
ax.set_title("Annotated plot")
ax.set_xlabel("Month")
ax.set_ylabel("Value")
ax.set_xticks(x)
ax.set_xticklabels(["Jan","Feb","Mar","Apr","May","Jun"],rotation=30)
ax.legend(loc="upper left")
ax.annotate("peak",xy=(5,8),xytext=(3.8,9),arrowprops=dict(arrowstyle="->"))
ax.grid(True,alpha=0.3)
plt.tight_layout()
plt.show()

#Images,imshow & colormaps
import matplotlib.pyplot as plt
import numpy as np
image=np.random.default_rng(42).random((20,20))
plt.imshow(image,cmap="viridis",interpolation="nearest")
plt.colorbar(label="Intensity")
plt.title("Image/Matrix Visualization")
plt.axis("off")
plt.show()

"""**XKCD** - Refers to a particular type of comic art & humar inspired by the webcomic XKCD.Created by Randall Munore. They are often popular for stick figures & simple black and white artwork.The comic covers a wide range of topics including Science, Mathematics and Technology."""

#XKCD Line plot
import matplotlib.pyplot as plt
plt.xkcd()
plt.plot([1,2,3,4],[1,2,3,4],'b-')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('XKCD Plot')
plt.show()

#XKCD style plot
import matplotlib.pyplot as plt
plt.xkcd()
plt.plot([1,2,3,4],[1,4,9,16],'b-')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('XKCD Style Plot')
plt.show()

#XKCD Bar plot
import matplotlib.pyplot as plt
plt.xkcd()
plt.bar(['A','B','C','D'],[10,20,15,25],color='g')
plt.xlabel('Categories')
plt.ylabel('Values')
plt.title('XKCD Style Bar Plot')
plt.show()

#XKCD Pi Plot
import matplotlib.pyplot as plt
plt.xkcd()
sizes=[15,30,45,10]
plt.pie(sizes,labels=['A','B','C','D'],autopct='%1.1f%%',startangle=90)
plt.title('XKCD Style Pie Plot')
plt.show()

#stop xkcd
import matplotlib.pyplot as plt
plt.rcdefaults()
plt.plot([1,2,3,4],[1,2,3,4],'b-')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('Normal Plot')
plt.show()

"""**Producing Graphs for Sounds**

Using for audio loading time domain processing, signal generation, spectral representations, magnitude scaling,music notation, frequency range generations,pitch & tuning.
"""

#Producing Graphs for Sounds
import matplotlib.pyplot as plt
import numpy as np
#Assuming audio_data is a numpy array containing audio samples
audio_data=np.random.randn(50)
#plotting the audio waveform
plt.plot(np.arange(len(audio_data)),audio_data)
plt.xlabel('Sample')
plt.ylabel('Amplitude')
plt.title('Basic Wave form audio')
#Display the plot
plt.show()

#Example -1
import matplotlib.pyplot as plt
import numpy as np
#Assuming audio_data is a numpy array containing audio samples
audio_data=np.random.randn(10000)
#Plotting the audio waveform
plt.plot(np.arange(len(audio_data)),audio_data)
plt.xlabel('Sample')
plt.ylabel('Amplitude')
plt.title('Wave form audio')
#Display the plot
plt.show()

#Example - 2
import matplotlib.pyplot as plt
import numpy as np
#Generating random audio data
#Sample rate in Hz
sample_rate=44100
#Duration of the audio in seconds
duration=5
#Creating a time array representing the time axis of the audio data
t=np.linspace(0,duration,int(sample_rate*duration))
#Generating audio data
#By creating a sine wave at 440 HZ frequency
audio_data=np.sin(2*np.pi*440*t)
#Plotting the spectogram of the audio data
plt.specgram(audio_data,Fs=sample_rate)
plt.xlabel(('Time(s)'))
plt.ylabel('Frequency')
plt.title('Spectogram')
#Adding a color bar to indicate intensity in decibles
plt.colorbar(label='Intensity(dB)')
#Display the plot
plt.show()

from google.colab import drive
drive.mount('/content/gdrive')

import matplotlib.pyplot as plt
import numpy as np
from scipy.io import wavfile # Import wavfile for reading .wav files
# Define the path to the WAV file
file_path = '/content/gdrive/My Drive/Colab Notebooks/Sound waves/Sound 1.wav'

# Read the WAV file
# wavfile.read returns a tuple: (sample_rate, audio_data)
samplerate, audio_data = wavfile.read(file_path)

# Plotting the audio waveform
plt.plot(np.arange(len(audio_data)),audio_data)
plt.xlabel('Sample')
plt.ylabel('Amplitude')
plt.title('Wave form audio')
plt.show()

"""**3D Plots** -- Used to visualize the data that has three dimensions (x,y and z). It is a part of the mpl_toolkits.Mplot3d module which is an extension for matplotlib."""

#Creating 3d figure object
import matplotlib.pyplot as plt
fig=plt.figure()
ax=plt.axes(projection='3d')
plt.show()

#3d Line plot
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
fig=plt.figure()
ax=plt.axes(projection='3d')
#defining all axis
z=np.linspace(0,1,100)
x=z*np.sin(25*z)
y=z*np.cos(25*z)
#Plotting
ax.plot3D(x,y,z,'green')
ax.set_title('3D Line Plot')
plt.show()

#3D Scatter Plot
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt
fig=plt.figure()
ax=plt.axes(projection='3d')
z=np.linspace(0,1,100)
x=z*np.sin(25*z)
y=z*np.cos(25*z)
c=x+y
ax.scatter(x,y,z,c=c)
ax.set_title('3D Scatter Plot')
plt.show()

#Histogram
import matplotlib.pyplot as plt
import numpy as np
data1=np.random.normal(1000)
data2=np.random.normal(loc=3,scale=1,size=1000)
plt.hist([data1,data2],bins=30,stacked=True,color=['cyan','purple'],edgecolor='black')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.title('Stacked Histogram')
plt.legend(['Dataset 1','Dataset 2'])
plt.show()